name: Build acbi-geth
on: 
 workflow_dispatch:
  inputs:
   version:
    description: 'geth binary version'
    required: true
    default: '1.0'
jobs:
  build_abci-geth:
    name: Build abci-geth
    strategy:
      matrix:
        include:
         - os: 'ubuntu-18.04'
           build_type: Release
         - os: 'macos-latest'
           build_type: Release
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: marlinprotocol/abci-geth
        submodules: recursive
    - name: Make
      run: make geth
