name: Test
on: 
 workflow_dispatch:
jobs:
  test-os:
    name: test Os
    strategy:
      matrix:
        include:
         - os: 'macos-latest'
           GOOS: darwin
           GOARCH: amd64
         - os: 'ubuntu-18.04'
           GOOS: linux
           GOARCH: amd64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        repository: whitewalker608/ActionsTest
    - uses: actions/setup-go@v2
    - name: GetOs
      run: go run getOsAndArch.go
    - name: TestOs
      run: echo ${{matrix.GOOS}}_${{matrix.GOARCH}}
